live_config_reload = true

[colors.bright]
black = "0x5C6370"
blue = "0x61AFEF"
cyan = "0x56B6C2"
green = "0x98C379"
magenta = "0xC678DD"
red = "0xE06C75"
white = "0xFFFFFF"
yellow = "0xE5C07B"

[colors.normal]
black = "0x282C34"
blue = "0x61AFEF"
cyan = "0x56B6C2"
green = "0x98C379"
magenta = "0xC678DD"
red = "0xE06C75"
white = "0xABB2BF"
yellow = "0xE5C07B"

[colors.primary]
background = "0x282C34"
foreground = "0xABB2BF"

[font]
size = 10.0

[font.bold]
family = "Noto Sans Mono"
style = "Regular"

[font.bold_italic]
family = "Noto Sans Mono"
style = "Bold Italic"

[font.italic]
family = "Noto Sans Mono"
style = "Italic"

[font.normal]
family = "Noto Sans Mono"
style = "Regular"

[scrolling]
history = 10000

[window]
opacity = 0.9
title = "Opportunity comes to those that are ready!"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 0
y = 0
